import Link from "next/link";
import { ArrowUpRight, ShieldCheck, Sparkles } from "lucide-react";
import { Logo } from "@/components/ui/Logo";

const LINKS = {
  "Sản phẩm":[{label:"Marketplace",href:"/san-pham"},{label:"Danh mục",href:"/danh-muc"},{label:"Thành viên VIP",href:"/thanh-vien"}],
  "Hỗ trợ":[{label:"Trung tâm trợ giúp",href:"/trung-tam-tro-giup"},{label:"Câu hỏi thường gặp",href:"/#faq"},{label:"Liên hệ",href:"/lien-he"},{label:"Zalo Admin · 0775893691",href:"https://zalo.me/0775893691"}],
  "Tài khoản":[{label:"Đăng nhập",href:"/dang-nhap"},{label:"Đăng ký",href:"/dang-ky"},{label:"Quên mật khẩu",href:"/quen-mat-khau"}]
};
export function SiteFooter(){return <footer className="relative mt-12 overflow-hidden border-t border-white/[.07] px-4 py-16 sm:px-8"><div className="pointer-events-none absolute inset-x-0 top-0 h-40 bg-[radial-gradient(ellipse_at_50%_0%,rgba(255,138,61,.08),transparent_68%)]"/><div className="relative mx-auto max-w-7xl"><div className="grid gap-12 sm:grid-cols-2 lg:grid-cols-4"><div className="lg:col-span-1"><Logo/><p className="mt-5 max-w-xs text-sm leading-6 text-white/38">Nền tảng thương mại số cao cấp, nơi mỗi sản phẩm và mỗi thao tác đều được thiết kế để tạo cảm giác đáng tin cậy.</p><div className="mt-5 inline-flex items-center gap-2 rounded-full border border-state-success/15 bg-state-success/[.045] px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[.12em] text-state-success"><ShieldCheck className="h-3.5 w-3.5"/> Trusted digital commerce</div></div>{Object.entries(LINKS).map(([heading,links])=><div key={heading}><h4 className="mb-4 text-xs font-semibold uppercase tracking-[.14em] text-white/50">{heading}</h4><ul className="space-y-3">{links.map(link=><li key={link.href}><Link href={link.href} className="group inline-flex items-center gap-1 text-sm text-white/42 transition-colors hover:text-white/85">{link.label}<ArrowUpRight className="h-3 w-3 opacity-0 transition-all group-hover:translate-x-0.5 group-hover:-translate-y-0.5 group-hover:opacity-60"/></Link></li>)}</ul></div>)}</div><div className="mt-14 flex flex-col justify-between gap-4 border-t border-white/[.06] pt-6 text-[11px] text-white/28 sm:flex-row"><span>© {new Date().getFullYear()} KhangHuynh Vault. Đã đăng ký bản quyền.</span><span className="inline-flex items-center gap-1.5"><Sparkles className="h-3 w-3 text-accent-orange"/> Built with intention.</span></div></div></footer>}
